### ISSUE TITLE
[REGRESSION] Can no longer run containers with --publish-service

### ISSUE THREAD

**Issue by tomdee** [docker/libnetwork#485]
This is a recent regression. I did not have this problem with older versions of docker.

This probably only affects drivers that set routes.

@mavenugo Has there been a recent change that affects the ordering of when networks come up relative to routes being set?

```
$ docker run --publish-service srvB.net1.calico --name workload-B -tid busybox
242d13c64258f5231e6cd0ee9a878661673a07b964be5a698cdb9d4bded50a7c
Error response from daemon: Cannot start container 242d13c64258f5231e6cd0ee9a878661673a07b964be5a698cdb9d4bded50a7c: failed sandbox add: failed to add interface tmp393e619a969 to sandbox: error setting interface "tmp393e619a969" routes to ["172.17.8.10/32"]: network is down
```

```
$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   e42789e
 Built:        Tue Sep  1 17:18:25 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   e42789e
 Built:        Tue Sep  1 17:18:25 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mavenugo** [comment]
@tomdee I dont know of any specific change that could have caused this issue. It will be useful if you can spot the version of docker experimental image that works. We havent done many vendor-in of libnetwork into docker after the 1.8 release. It should be easy to spot a broken image if you just try those images pre and post vendor-in.

**Comment by tomdee** [comment]
I've found the exact docker revision that caused this regression - https://github.com/docker/docker/commit/7948b755c77a3901ffb5b397659c72ae4e6f4340

**Comment by tomdee** [comment]
@mrjana you did the netlink merge, would you be able to take a look at this issue?
@mavenugo Should I raise this issue on docker/docker or is it best tracked here?

**Comment by lxpollitt** [comment]
@mrjana @mavenugo ^^

**Comment by mavenugo** [comment]
@lxpollitt @tomdee thanks for narrowing down the issue seen in vishvananda/netlink project. Can you please debug it in the netlink library and fix it ? We can vendor the netlink package once it is resolved.

**Comment by lxpollitt** [comment]
@mavenugo: @tomdee is on vacation, and he would be the best candidate in my team to look further into this.  However, I don't think he (or anyone on my team) are best placed to resolve this regression.  We have zero expertise on the `vishvananda/netlink` project, little knowledge of how libnetwork uses it, and no knowledge of what the "to fix certain wierd netlink issues seen" were that triggered @mrjana to make this change.

Is there anyone in the libnetwork team, or elsewhere in Docker who could look into resolving this regression?  @mrjana perhaps, since he might be the person most familiar with the library?

**Comment by mavenugo** [comment]
@lxpollitt please have your team take a look @ https://github.com/vishvananda/netlink/pull/44 to get more information on the netlink issue seen & eventually resolved in this `vishvananda/netlink` package.
Needless to say, expertise is built by spending time understanding the code & fixing issues. Especially when we are dependent on external packages like the netlink library. Since none of us are seeing this issue & it seems to be calico specific, I would request you to spend some time debugging it and feel free to push a vendor-in patch if you have identified the root-cause. We can certainly help once we handle higher priority stuff (there is a lot of it) that impacts libnetwork directly.

**Comment by lxpollitt** [comment]
@mavenugo My understanding from Tom is that this would impact any driver that uses libnetwork to set routes. (i.e. He thinks it is a regression that impacts libnetwork in general, not a Calico regression.)

**Comment by mrjana** [comment]
@lxpollitt @tomdee Not sure how this can be a libnetwork regression. There is even a test case here https://github.com/docker/libnetwork/blob/master/osl/sandbox_linux_test.go#L77
to actually test this exact case and it seems to be succeeding. Did anything change in your side? Also can you make sure and if this issue is still seen with the latest docker experimental because one important namespace bug is fixed there that may have something to do with it.

**Comment by lxpollitt** [comment]
@mrjana Good question. @tomdee didn't think so, in that I believe he narrowed it down to the specific checkin he referenced above.  But I'll let him comment when he's back from vacation, including figuring out what is different between the test case you reference and what Calico is trying to do.

**Comment by tomdee** [comment]
I can confirm that this still isn't working on the latest docker build.

@mrjana Is that test actually trying to do the netlink operations? Or are they mocked out?

**Comment by mrjana** [comment]
@tomdee It does the actual netlink operation. Nothing's mocked out. So not sure how we can repro your failure in a simple test case

**Comment by tomdee** [comment]
OK, I've narrowed it down to a single missing line that's causing the problem. 

If you add this one line back into the vendored in version of netlink in docker then the Calico plugin starts working again - https://github.com/vishvananda/netlink/commit/5dd6b277e6612183e1763a43c30164dcd74dd562#diff-350920f2216bdd28aa0ddd41f71bcab0L122

I have no idea why this is the case. @mrjana can you make any guesses as to why this line might matter?

**Comment by mrjana** [comment]
@tomdee Hmm.. Do you use veth interfaces in your driver? If so, did you set the host side interface to link up before you returned from Join call?

**Comment by tomdee** [comment]
Yes, we use veth interfaces. We set both sides of the veth to UP before returning from the Join call. Should we only be setting the host side?

**Comment by tomdee** [comment]
@mrjana @mavenugo 

Actually, looking again, we're only setting the side of the veth that stays in the host to be UP.

However, I've tried setting both sides to up but it's still not working.

I've just checked and the process of pushing a veth into the namespace sets it to DOWN (using `ip link <NAME> set netns <NS_NAME>`. When is libnetwork setting it back to UP?

**Comment by tomdee** [comment]
@mrjana OK, found it. interface.linux.go sets the interface to state DOWN which means it can't possibly set the routes.

I've got not idea why the test referenced above passes...

```
		// Down the interface before configuring
		if err := netlink.LinkSetDown(iface); err != nil {
			return fmt.Errorf("failed to set link down: %v", err)
		}

		// Configure the interface now this is moved in the proper namespace.
		if err := configureInterface(iface, i); err != nil {
			return err
		}

		// Up the interface.
		if err := netlink.LinkSetUp(iface); err != nil {
			return fmt.Errorf("failed to set link up: %v", err)
		}
```

**Comment by mrjana** [comment]
@tomdee Thanks for taking a look at this. It is indeed a puzzle how that test case is passing. Let me see. The test case was added by someone in project Calico so you might as well ask around in your team while I investigate.
